apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-filter-ms
  labels:
    app: content-filter-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-filter-ms
  template:
    metadata:
      labels:
        app: content-filter-ms
    spec:
      containers:
        - name: content-filter-ms
          image: islamahmad/content-filter-ms:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: AUTHENTICATE_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: content-filter-ms
                  key: AUTHENTICATE_SERVICE