apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-filter-ms
  labels:
    app: content-filter-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-filter-ms
  template:
    metadata:
      labels:
        app: content-filter-ms
    spec:
      containers:
        - name: content-filter-ms
          image: islamahmad/eaproj-content-filter-ms:1.0.10
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "8080"

          envFrom:
            - configMapRef:
                name: services-global
            - configMapRef:
                name: kafka-global
