apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-filter-ms
  labels:
    app: content-filter-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-filter-ms
  template:
    metadata:
      labels:
        app: content-filter-ms
    spec:
      containers:
        - name: content-filter-ms
          image: islamahmad/eaproj-content-filter-ms:1.0.8
          imagePullPolicy: Always
          env:
            #KAFKA
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: services-global
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: TOPIC_BAN_QUESTION
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: TOPIC_BAN_QUESTION
            - name: TOPIC_BAN_ANSWER
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: TOPIC_BAN_ANSWER
            - name: TOPIC_BAN_QUESTION_COMMENT
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: TOPIC_BAN_QUESTION_COMMENT
            - name: TOPIC_BAN_ANSWER_COMMENT
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: TOPIC_BAN_ANSWER_COMMENT
            - name: TOPIC_NEW_QUESTION
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: TOPIC_NEW_QUESTION
            - name: SUBS_NEW_QUESTION_FILTER
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: SUBS_NEW_QUESTION_FILTER
            - name: TOPIC_NEW_ANSWER
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: TOPIC_NEW_ANSWER
            - name: SUBS_NEW_ANSWER_FILTER
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: SUBS_NEW_ANSWER_FILTER
            - name: TOPIC_NEW_QUESTION_COMMENT
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: TOPIC_NEW_QUESTION_COMMENT
            - name: SUBS_NEW_QUESTION_COMMENT_FILTER
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: SUBS_NEW_QUESTION_COMMENT_FILTER
            - name: TOPIC_NEW_ANSWER_COMMENT
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: TOPIC_NEW_ANSWER_COMMENT
            - name: SUBS_NEW_ANSWER_COMMENT_FILTER
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: SUBS_NEW_ANSWER_COMMENT_FILTER
